#pragma once

#include <iostream>
#include <vector>
#include <cstring>
#include <string>
#include <set>
#include <map>
#include <queue>
#include <deque>
#include <stack>
#include <utility>
#include <iomanip>
#include <algorithm>
#include <cmath>
#include <climits>
#include <cstdlib>
#include <fstream>
#include <cassert>
#include <sstream>
#include <csignal>
#include <utility>
#include <sstream>
/* sockets includes */
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <fcntl.h>
#include <unistd.h>
#include <poll.h>

/*built-in headers*/
#include "../Bot/Bot.hpp"
#include "Client.hpp"
#include "Channel.hpp"
#include "Server.hpp"
#include "Commands.hpp"
#include "Replies.hpp"